- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 instance
      ec2:
        instance_type: t2.small
        image: ami-0885b1f6bd170450c
        region: us-east-1
        key_name: test
        vpc_subnet_id: subnet-26edb96b
        assign_public_ip: yes
        wait: yes
        count: 1
        group: eshop
        aws_access_key: ASIA2ERR3H2PAZ3L73IK
        aws_secret_key: QYWSxkeNRWiSlRC65/v+DuPMOu0MMPAzVenwgiUv
        security_token: FwoGZXIvYXdzEBEaDMH8XhiejnkMFkmiAiK/AUPuOtr77YxutMVys0dEKIyW+dmUof4Snw9Ro8oO57EzACooWJSWC/gOIgt1ivjrPkP0rOMGPkUolwftNsDOd4DNui/Y6d28hNvurJ96gfBCyjOA9yVoFQ/PwOXD2IhYMtPIdxjyhRC9DMpez82rCAc70CHN24VSGSIjlOT3iinDcmtMU4oO/m4UPSUrhditDKptOGBlUT6jcdh5c5neSpelyTCVJq00zAEJdcz+ux3jyquWm94dWDnKwR7vvEz4KMSliP8FMi10RInxX3YB0KNmTogdqtRjaIpRpt+QpQNRuGwxSSB4N+C9SpULDwy/B1oV76g=
      register: ec2

    - name: Add instance host to group
      add_host: hostname={{ item.public_dns_name }} groupname=launched
      with_items: '{{ec2.instances}}'

    - name: Wait for SSH connection
      wait_for: host= {{ item.public_dns_name }}  port =22 delay=30 timeout=300 state=started
      with_items: '{{ec2.instances}}'

- name: Configure EC2
  hosts: localhost
  connection: ssh

  tasks:
    - name: Install docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      become: yes
    - service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Get docker from github
      git:
        repo: 'https://github.com/rinamoon/Devops_Semestralni_Prace.git'
        dest: ./app
    - name: Build docker with eshop
      shell: cd app && docker build -t myeshop:latest .
      become: yes
    - name: Run docker with eshop
      shell: docker run -p 80:3000 myeshop
      async: 45
      poll: 10
      become: yes
    - wait_for:
        port: 80
